### ISSUE TITLE
Compatibility with firegento/magento2-content-provisioning >= 1.2.0

### ISSUE THREAD

**Issue by roma-glushko** [techdivision/pagedesigner-content-provisioning#1]
**Description**
We need to make TechDivision_PageDesignerContentProvisioning module compatible with Firegento_ContentProvisioning >= 1.2.0. 

Currently, after renaming `Firegento\ContentProvisioning\Model\Config\Parser\Query\FetchMediaFilesFromContent` in the recent versions, we get an error because PageDesignerContentProvisioning depends on the old classname.

**Comment by vadimjustus** [comment]
Merged and tagged
